apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
type: Opaque
stringData:
  FORGEJO_DB_USER: {{ .Values.forgejo.credentials.dbUser | b64dec }}
  FORGEJO_DB_PASS: {{ .Values.forgejo.credentials.dbPass | b64dec }}
  FORGEJO_SECRET_KEY: {{ .Values.forgejo.credentials.secretKey | b64dec }}
